version: '3.8'
services:
  api-app:
    image: arian-api-app:latest
    build:
      dockerfile: apiApp/Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_URLS: "http://+"
    deploy:
      restart_policy:
        condition: on-failure
